### ISSUE TITLE
有再次更新php扩展的想法

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xiaoyjy/cconv#17]
```
被iconv折腾了很久才发现这个cconv这个好东西。

但是我却编译不上php 的扩展模块。

有再次更新的想法吗？

谢谢

```

Original issue reported on code.google.com by `huangq...@zhihuiya.com` on 29 Mar 2012 at 6:57

**Comment by xiaoyjy** [comment]
diff --git a/php_cconv.c b/php_cconv.c
index 71ea680..3dfaec4 100644
--- a/php_cconv.c
+++ b/php_cconv.c
@@ -6,7 +6,7 @@
        #include "config.h"
 #endif
 
-static function_entry cconv_functions[] = {
+static zend_function_entry cconv_functions[] = {
     PHP_FE(cconv, NULL)
     {NULL, NULL, NULL}
 };

**Comment by xiaoyjy** [comment]
OK了
